[package]
authors = ["Erik Johnston"]
name = "rust-synapse-find-unreferenced-state-groups"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "3.0.14", features = ["cargo"] }
indicatif = "0.16.2"
postgres = "0.19.2"
